/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author UddhavZ
 */
public class HospAdminLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospAdminJPanel
     */
    public HospAdminLoginJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHospUsername = new javax.swing.JTextField();
        lblHospPassword = new javax.swing.JLabel();
        pfHospPassword = new javax.swing.JPasswordField();
        lblHospAdminTitle = new javax.swing.JLabel();
        btnHospLogin = new javax.swing.JButton();
        lblHospUsername = new javax.swing.JLabel();

        lblHospPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblHospPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospPassword.setText("Password :");
        lblHospPassword.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblHospAdminTitle.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        lblHospAdminTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospAdminTitle.setText("Hospital Admin Login");
        lblHospAdminTitle.setToolTipText("");
        lblHospAdminTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHospLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnHospLogin.setText("Login");
        btnHospLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospLoginActionPerformed(evt);
            }
        });

        lblHospUsername.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblHospUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospUsername.setText("Username :");
        lblHospUsername.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 312, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHospAdminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHospUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHospPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pfHospPassword)
                                .addComponent(txtHospUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnHospLogin)))
                        .addGap(439, 439, 439))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospAdminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHospUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHospUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHospPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfHospPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHospLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHospLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHospLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHospLogin;
    private javax.swing.JLabel lblHospAdminTitle;
    private javax.swing.JLabel lblHospPassword;
    private javax.swing.JLabel lblHospUsername;
    private javax.swing.JPasswordField pfHospPassword;
    private javax.swing.JTextField txtHospUsername;
    // End of variables declaration//GEN-END:variables
}
