/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author UddhavZ
 */
public class SysAdminLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminJPanel
     */
    public SysAdminLoginJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSysAdminTitle = new javax.swing.JLabel();
        lblSysUsername = new javax.swing.JLabel();
        txtSysUsername = new javax.swing.JTextField();
        lblSysPassword = new javax.swing.JLabel();
        pfSysPassword = new javax.swing.JPasswordField();
        btnSysLogin = new javax.swing.JButton();

        lblSysAdminTitle.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        lblSysAdminTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSysAdminTitle.setText("System Admin Login");
        lblSysAdminTitle.setToolTipText("");
        lblSysAdminTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSysUsername.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSysUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSysUsername.setText("Username :");
        lblSysUsername.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblSysPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSysPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSysPassword.setText("Password :");
        lblSysPassword.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnSysLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnSysLogin.setText("Login");
        btnSysLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSysAdminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSysUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSysPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pfSysPassword)
                                .addComponent(txtSysUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSysLogin)
                                .addGap(78, 78, 78)))
                        .addGap(438, 438, 438))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSysAdminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSysUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSysUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSysPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfSysPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSysLogin)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSysLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysLoginActionPerformed
        // TODO add your handling code here:
        SysAdminMainFrame sysmain = new SysAdminMainFrame();
        sysmain.setVisible(true);
        //jSplitPane1.setRightComponent(sysadminPanel);
    }//GEN-LAST:event_btnSysLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSysLogin;
    private javax.swing.JLabel lblSysAdminTitle;
    private javax.swing.JLabel lblSysPassword;
    private javax.swing.JLabel lblSysUsername;
    private javax.swing.JPasswordField pfSysPassword;
    private javax.swing.JTextField txtSysUsername;
    // End of variables declaration//GEN-END:variables
}
