/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.*;


/**
 *
 * @author UddhavZ
 */
public class SysAdminMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form SysAdminMainFrame
     */
    JPanel mainPanel = new JPanel();
    Person selectedPerson = new Person();
    Patient selectedPatient = new Patient();
    PersonDirectory prd;
    
    public SysAdminMainFrame() {
        initComponents();
        this.mainPanel = mainPanel;
        refreshTable();
    }
    
    public void refreshTable(){
//        int rowCount = tblPersons.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblPersons.getModel();
        model.setRowCount(0);
        
        for(Person person: prd.getPersonDirectory()){
            Object row[] = new Object[8];
            row[0] = person.getName();
            row[1] = person.getAge();
            row[2] = person.getPhoneNumber();
            row[3] = person.getCity().getCityName();
            row[4] = person.getZipCode();
            row[5] = person.getCommunity().getCommunityName();
            row[6] = person.getHouse().getHouseName();
            row[7] = person.getGender();
            model.addRow(row);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sysadminFrametitleJPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        systemadminMainJPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        sysadminAddPersonJPanel = new javax.swing.JPanel();
        lblPanelTitle = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblPersonAge = new javax.swing.JLabel();
        lblPersonCity = new javax.swing.JLabel();
        lblPersonPhoneNo = new javax.swing.JLabel();
        lblPersonZipcode = new javax.swing.JLabel();
        lblPersonCommunity = new javax.swing.JLabel();
        lblPersonHouse = new javax.swing.JLabel();
        lblPersonBirthDate = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbOther = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPhonenumber = new javax.swing.JTextField();
        txtZipcode = new javax.swing.JTextField();
        dStartDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        cbCity = new javax.swing.JComboBox<>();
        cbCommunity = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        sysadminPersonJPanel = new javax.swing.JPanel();
        txtPersonSearch = new javax.swing.JTextField();
        lblPersonSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersons = new javax.swing.JTable();
        btnAddAsPatient = new javax.swing.JButton();
        sysadminPatientJPanel = new javax.swing.JPanel();
        lblPatientSearch = new javax.swing.JLabel();
        txtPatientSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        addVisitJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientId = new javax.swing.JLabel();
        patientName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSYS = new javax.swing.JTextField();
        txtOxygenLevel = new javax.swing.JTextField();
        txtRespiratoryRate = new javax.swing.JTextField();
        btnAddVitalSigns = new javax.swing.JButton();
        lblSYSValidation = new javax.swing.JLabel();
        lblOxygenLevelValidation = new javax.swing.JLabel();
        lblRespiratoryRateValidation = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBodyTemperature = new javax.swing.JTextField();
        lblBodyTemperatureValidation = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDIA = new javax.swing.JTextField();
        lblDIAValidation = new javax.swing.JLabel();
        btnAddVisit = new javax.swing.JButton();
        sysadminDoctorJPanel = new javax.swing.JPanel();
        sysadminHospitalJPanel = new javax.swing.JPanel();
        sysadminEncounterJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lblTitle.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SYstem Admin");

        javax.swing.GroupLayout sysadminFrametitleJPanelLayout = new javax.swing.GroupLayout(sysadminFrametitleJPanel);
        sysadminFrametitleJPanel.setLayout(sysadminFrametitleJPanelLayout);
        sysadminFrametitleJPanelLayout.setHorizontalGroup(
            sysadminFrametitleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminFrametitleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                .addContainerGap())
        );
        sysadminFrametitleJPanelLayout.setVerticalGroup(
            sysadminFrametitleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminFrametitleJPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(sysadminFrametitleJPanel);

        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        sysadminAddPersonJPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        lblPanelTitle.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lblPanelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPanelTitle.setText("Person Information");

        lblPersonName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonName.setText("Name :");
        lblPersonName.setToolTipText("");
        lblPersonName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblPersonAge.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonAge.setText("Age :");
        lblPersonAge.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblPersonCity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonCity.setText("City :");
        lblPersonCity.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblPersonPhoneNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonPhoneNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonPhoneNo.setText("Phone Number :");
        lblPersonPhoneNo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblPersonZipcode.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonZipcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonZipcode.setText("Zipcode :");
        lblPersonZipcode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblPersonCommunity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonCommunity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonCommunity.setText("Community :");
        lblPersonCommunity.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblPersonHouse.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonHouse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonHouse.setText("House Address :");
        lblPersonHouse.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblPersonBirthDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblPersonBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonBirthDate.setText("Birth Date :");
        lblPersonBirthDate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        rbOther.setText("Other");
        rbOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOtherActionPerformed(evt);
            }
        });

        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });

        dStartDate.setDateFormatString("dd-MM-yyyy");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Gender :");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        cbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Boston", "New York" }));

        cbCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jButton1.setText("SAVE");

        javax.swing.GroupLayout sysadminAddPersonJPanelLayout = new javax.swing.GroupLayout(sysadminAddPersonJPanel);
        sysadminAddPersonJPanel.setLayout(sysadminAddPersonJPanelLayout);
        sysadminAddPersonJPanelLayout.setHorizontalGroup(
            sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPanelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMale)
                        .addGap(30, 30, 30)
                        .addComponent(rbFemale)
                        .addGap(32, 32, 32)
                        .addComponent(rbOther))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCommunity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipcode))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonCity, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhonenumber))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonAge, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        sysadminAddPersonJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbCity, cbCommunity, dStartDate, jScrollPane2, txtAge, txtName, txtPhonenumber, txtZipcode});

        sysadminAddPersonJPanelLayout.setVerticalGroup(
            sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminAddPersonJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblPanelTitle)
                .addGap(18, 18, 18)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMale)
                    .addComponent(rbOther)
                    .addComponent(rbFemale)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonBirthDate)
                    .addComponent(dStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonPhoneNo)
                    .addComponent(txtPhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonZipcode)
                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonCity)
                    .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonCommunity)
                    .addComponent(cbCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sysadminAddPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonHouse)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        sysadminAddPersonJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblPersonBirthDate, rbFemale, rbMale, rbOther});

        jTabbedPane1.addTab("Add New Person", sysadminAddPersonJPanel);

        sysadminPersonJPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        txtPersonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonSearchActionPerformed(evt);
            }
        });

        lblPersonSearch.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPersonSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonSearch.setText("Search:");

        jScrollPane1.setBorder(null);

        tblPersons.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tblPersons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Phone number", "City", "Zip code", "Community name", "House address", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPersons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPersons.setShowGrid(false);
        tblPersons.getTableHeader().setReorderingAllowed(false);
        tblPersons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPersonsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersons);

        btnAddAsPatient.setText("add as Patient");
        btnAddAsPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAsPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sysadminPersonJPanelLayout = new javax.swing.GroupLayout(sysadminPersonJPanel);
        sysadminPersonJPanel.setLayout(sysadminPersonJPanelLayout);
        sysadminPersonJPanelLayout.setHorizontalGroup(
            sysadminPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminPersonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sysadminPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sysadminPersonJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPersonSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sysadminPersonJPanelLayout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(btnAddAsPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sysadminPersonJPanelLayout.setVerticalGroup(
            sysadminPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminPersonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sysadminPersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonSearch)
                    .addComponent(txtPersonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAsPatient)
                .addContainerGap(500, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Person", sysadminPersonJPanel);

        lblPatientSearch.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPatientSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientSearch.setText("Search:");

        txtPatientSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientSearchActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Age", "Phone number", "City", "Zip code", "Community name", "House address", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatient.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPatient.getTableHeader().setReorderingAllowed(false);
        tblPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPatientMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblPatient);

        addVisitJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Patient ID:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Patient Name:");

        patientId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        patientName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Blood Pressure SYS (mmhg):");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Oxygen Level:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Respiratory Rate (BPM):");

        txtSYS.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtSYS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSYSFocusGained(evt);
            }
        });
        txtSYS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSYSKeyTyped(evt);
            }
        });

        txtOxygenLevel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtOxygenLevel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOxygenLevelFocusGained(evt);
            }
        });
        txtOxygenLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOxygenLevelKeyTyped(evt);
            }
        });

        txtRespiratoryRate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtRespiratoryRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRespiratoryRateFocusGained(evt);
            }
        });
        txtRespiratoryRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespiratoryRateKeyTyped(evt);
            }
        });

        btnAddVitalSigns.setText("Add Vital signs");
        btnAddVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVitalSignsActionPerformed(evt);
            }
        });

        lblSYSValidation.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblSYSValidation.setForeground(new java.awt.Color(255, 0, 51));
        lblSYSValidation.setText("jLabel2");

        lblOxygenLevelValidation.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblOxygenLevelValidation.setForeground(new java.awt.Color(255, 0, 51));
        lblOxygenLevelValidation.setText("jLabel2");

        lblRespiratoryRateValidation.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblRespiratoryRateValidation.setForeground(new java.awt.Color(255, 0, 51));
        lblRespiratoryRateValidation.setText("jLabel2");

        jLabel7.setFont(new java.awt.Font("Menlo", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VITAL SIGNS");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("Body Temperature:");

        txtBodyTemperature.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtBodyTemperature.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBodyTemperatureFocusGained(evt);
            }
        });
        txtBodyTemperature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBodyTemperatureKeyTyped(evt);
            }
        });

        lblBodyTemperatureValidation.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblBodyTemperatureValidation.setForeground(new java.awt.Color(255, 0, 51));
        lblBodyTemperatureValidation.setText("jLabel2");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setText("Blood Pressure DIA (mmhg):");

        txtDIA.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtDIA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDIAFocusGained(evt);
            }
        });
        txtDIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDIAKeyTyped(evt);
            }
        });

        lblDIAValidation.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblDIAValidation.setForeground(new java.awt.Color(255, 0, 51));
        lblDIAValidation.setText("jLabel2");

        javax.swing.GroupLayout addVisitJPanelLayout = new javax.swing.GroupLayout(addVisitJPanel);
        addVisitJPanel.setLayout(addVisitJPanelLayout);
        addVisitJPanelLayout.setHorizontalGroup(
            addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVisitJPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addVisitJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblOxygenLevelValidation)
                                .addComponent(txtOxygenLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addVisitJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRespiratoryRateValidation)
                                .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addVisitJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(addVisitJPanelLayout.createSequentialGroup()
                                    .addComponent(patientId)
                                    .addGap(250, 250, 250)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(patientName))))
                        .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddVitalSigns)
                            .addGroup(addVisitJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBodyTemperatureValidation)
                                    .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVisitJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSYSValidation)
                                .addComponent(txtSYS, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addVisitJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDIAValidation)
                            .addComponent(txtDIA, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100))
        );
        addVisitJPanelLayout.setVerticalGroup(
            addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVisitJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addVisitJPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(patientId)))
                    .addGroup(addVisitJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(patientName))))
                .addGap(40, 40, 40)
                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtSYS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSYSValidation)
                .addGap(5, 5, 5)
                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDIA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDIAValidation)
                .addGap(6, 6, 6)
                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOxygenLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOxygenLevelValidation)
                .addGap(6, 6, 6)
                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRespiratoryRateValidation)
                .addGap(9, 9, 9)
                .addGroup(addVisitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBodyTemperatureValidation)
                .addGap(18, 18, 18)
                .addComponent(btnAddVitalSigns, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnAddVisit.setText("Add Visit");

        javax.swing.GroupLayout sysadminPatientJPanelLayout = new javax.swing.GroupLayout(sysadminPatientJPanel);
        sysadminPatientJPanel.setLayout(sysadminPatientJPanelLayout);
        sysadminPatientJPanelLayout.setHorizontalGroup(
            sysadminPatientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminPatientJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sysadminPatientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sysadminPatientJPanelLayout.createSequentialGroup()
                        .addComponent(addVisitJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnAddVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sysadminPatientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(sysadminPatientJPanelLayout.createSequentialGroup()
                            .addComponent(lblPatientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPatientSearch))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sysadminPatientJPanelLayout.setVerticalGroup(
            sysadminPatientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminPatientJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sysadminPatientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientSearch)
                    .addComponent(txtPatientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sysadminPatientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVisitJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patient", sysadminPatientJPanel);

        sysadminDoctorJPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout sysadminDoctorJPanelLayout = new javax.swing.GroupLayout(sysadminDoctorJPanel);
        sysadminDoctorJPanel.setLayout(sysadminDoctorJPanelLayout);
        sysadminDoctorJPanelLayout.setHorizontalGroup(
            sysadminDoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        sysadminDoctorJPanelLayout.setVerticalGroup(
            sysadminDoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Doctor", sysadminDoctorJPanel);

        sysadminHospitalJPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout sysadminHospitalJPanelLayout = new javax.swing.GroupLayout(sysadminHospitalJPanel);
        sysadminHospitalJPanel.setLayout(sysadminHospitalJPanelLayout);
        sysadminHospitalJPanelLayout.setHorizontalGroup(
            sysadminHospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        sysadminHospitalJPanelLayout.setVerticalGroup(
            sysadminHospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hospital", sysadminHospitalJPanel);

        sysadminEncounterJPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout sysadminEncounterJPanelLayout = new javax.swing.GroupLayout(sysadminEncounterJPanel);
        sysadminEncounterJPanel.setLayout(sysadminEncounterJPanelLayout);
        sysadminEncounterJPanelLayout.setHorizontalGroup(
            sysadminEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        sysadminEncounterJPanelLayout.setVerticalGroup(
            sysadminEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Encounter", sysadminEncounterJPanel);

        javax.swing.GroupLayout systemadminMainJPanelLayout = new javax.swing.GroupLayout(systemadminMainJPanel);
        systemadminMainJPanel.setLayout(systemadminMainJPanelLayout);
        systemadminMainJPanelLayout.setHorizontalGroup(
            systemadminMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1089, Short.MAX_VALUE)
            .addGroup(systemadminMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(systemadminMainJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
        systemadminMainJPanelLayout.setVerticalGroup(
            systemadminMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
            .addGroup(systemadminMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(systemadminMainJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );

        jSplitPane1.setRightComponent(systemadminMainJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonSearchActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOtherActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void tblPersonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPersonsMouseClicked

    private void tblPersonsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonsMousePressed
        // TODO add your handling code here:
        int row = tblPersons.rowAtPoint( evt.getPoint() );
        this.selectedPerson = PersonDirectory.personDirectory.get(row);
    }//GEN-LAST:event_tblPersonsMousePressed

    private void btnAddAsPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAsPatientActionPerformed
        // TODO add your handling code here:

        if (selectedPerson.getName() == null) {
            JOptionPane.showMessageDialog(null, "Please select a person from the table first", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (isAlreayAdded()) {
                JOptionPane.showMessageDialog(this, "Person already in Patient list",  "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                addPersonAsPatient();
                selectedPerson = new Person();
                tblPersons.clearSelection();
                JOptionPane.showMessageDialog(this, "Person successfully added as Patient");
            }
        }
    }//GEN-LAST:event_btnAddAsPatientActionPerformed

    private void txtPatientSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientSearchActionPerformed

    private void tblPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPatientMouseClicked

    private void tblPatientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMousePressed
        // TODO add your handling code here:
        int row = tblPatient.rowAtPoint( evt.getPoint() );
        this.selectedPatient = PatientDirectory.patientDirectory.get(row);
    }//GEN-LAST:event_tblPatientMousePressed

    private void txtSYSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSYSFocusGained
        // TODO add your handling code here:
        lblSYSValidation.setVisible(false);
    }//GEN-LAST:event_txtSYSFocusGained

    private void txtSYSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSYSKeyTyped
        // TODO add your handling code here:
        allowOnlyDigitValidation(evt);
    }//GEN-LAST:event_txtSYSKeyTyped

    private void txtOxygenLevelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOxygenLevelFocusGained
        // TODO add your handling code here:
        lblOxygenLevelValidation.setVisible(false);
    }//GEN-LAST:event_txtOxygenLevelFocusGained

    private void txtOxygenLevelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOxygenLevelKeyTyped
        // TODO add your handling code here:
        allowOnlyDigitValidation(evt);
    }//GEN-LAST:event_txtOxygenLevelKeyTyped

    private void txtRespiratoryRateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRespiratoryRateFocusGained
        // TODO add your handling code here:
        lblRespiratoryRateValidation.setVisible(false);
    }//GEN-LAST:event_txtRespiratoryRateFocusGained

    private void txtRespiratoryRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespiratoryRateKeyTyped
        // TODO add your handling code here:
        //        allowOnlyDigitValidation(evt);
    }//GEN-LAST:event_txtRespiratoryRateKeyTyped

    private void btnAddVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVitalSignsActionPerformed
        // TODO add your handling code here:
        if (isValidData()) {
            addVitalSigns();
            clearData();
        }
    }//GEN-LAST:event_btnAddVitalSignsActionPerformed

    private void txtBodyTemperatureFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBodyTemperatureFocusGained
        // TODO add your handling code here:
        lblBodyTemperatureValidation.setVisible(false);
    }//GEN-LAST:event_txtBodyTemperatureFocusGained

    private void txtBodyTemperatureKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBodyTemperatureKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodyTemperatureKeyTyped

    private void txtDIAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDIAFocusGained
        // TODO add your handling code here:
        lblDIAValidation.setVisible(false);
    }//GEN-LAST:event_txtDIAFocusGained

    private void txtDIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDIAKeyTyped
        // TODO add your handling code here:
        allowOnlyDigitValidation(evt);
    }//GEN-LAST:event_txtDIAKeyTyped

    private Boolean isAlreayAdded() {
        Boolean isAdded = false;
        
        for (Patient patient: PatientDirectory.patientDirectory) {
            if (patient.getPhoneNumber() == selectedPerson.getPhoneNumber()) {
                isAdded = true;
                break;
            }
        }
        return isAdded;
    }
    
    private void addPersonAsPatient() {
        Patient patient = new Patient();
        
        Random r = new Random( System.currentTimeMillis() );
        patient.setPatientID((1 + r.nextInt(2)) * 10000 + r.nextInt(10000));
        
        House house = new House();
        Community community = new Community();
        City city = new City();

        house.setHouseName(selectedPerson.getHouse().getHouseName());        
        community.setCommunityName(selectedPerson.getCommunity().getCommunityName());
        city.setCityName(selectedPerson.getCity().getCityName());

        patient.setHouse(house);
        patient.setCommunity(community);
        patient.setCity(city);
        patient.setName(selectedPerson.getName());
        patient.setAge(selectedPerson.getAge());
        patient.setPhoneNumber(selectedPerson.getPhoneNumber());
        patient.setZipCode(selectedPerson.getZipCode());
        patient.setGender(selectedPerson.getGender());
        
        PatientDirectory.patientDirectory.add(patient);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SysAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SysAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SysAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SysAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysAdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addVisitJPanel;
    private javax.swing.JButton btnAddAsPatient;
    private javax.swing.JButton btnAddVisit;
    private javax.swing.JButton btnAddVitalSigns;
    private javax.swing.JComboBox<String> cbCity;
    private javax.swing.JComboBox<String> cbCommunity;
    private com.toedter.calendar.JDateChooser dStartDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBodyTemperatureValidation;
    private javax.swing.JLabel lblDIAValidation;
    private javax.swing.JLabel lblOxygenLevelValidation;
    private javax.swing.JLabel lblPanelTitle;
    private javax.swing.JLabel lblPatientSearch;
    private javax.swing.JLabel lblPersonAge;
    private javax.swing.JLabel lblPersonBirthDate;
    private javax.swing.JLabel lblPersonCity;
    private javax.swing.JLabel lblPersonCommunity;
    private javax.swing.JLabel lblPersonHouse;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblPersonPhoneNo;
    private javax.swing.JLabel lblPersonSearch;
    private javax.swing.JLabel lblPersonZipcode;
    private javax.swing.JLabel lblRespiratoryRateValidation;
    private javax.swing.JLabel lblSYSValidation;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel patientId;
    private javax.swing.JLabel patientName;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JRadioButton rbOther;
    private javax.swing.JPanel sysadminAddPersonJPanel;
    private javax.swing.JPanel sysadminDoctorJPanel;
    private javax.swing.JPanel sysadminEncounterJPanel;
    private javax.swing.JPanel sysadminFrametitleJPanel;
    private javax.swing.JPanel sysadminHospitalJPanel;
    private javax.swing.JPanel sysadminPatientJPanel;
    private javax.swing.JPanel sysadminPersonJPanel;
    private javax.swing.JPanel systemadminMainJPanel;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTable tblPersons;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBodyTemperature;
    private javax.swing.JTextField txtDIA;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOxygenLevel;
    private javax.swing.JTextField txtPatientSearch;
    private javax.swing.JTextField txtPersonSearch;
    private javax.swing.JTextField txtPhonenumber;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtSYS;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables

    private void allowOnlyDigitValidation(java.awt.event.KeyEvent evt) {
        char pressedKey = evt.getKeyChar();
        
        if(Character.isAlphabetic(pressedKey)) {
            evt.consume();
        }
    }
    
    // To check every validation of all fields
    private boolean isValidData() {
        boolean isValid = true;
        
        if (txtSYS.getText().isBlank()) {
            isValid = false;
            hideShowValidation(lblSYSValidation, "Please enter Blood pressure SYS");
            
        } 
         
        if (txtDIA.getText().isBlank()) {
            isValid = false;
            hideShowValidation(lblDIAValidation, "Please enter Blood pressure DIA");
            
        } 
        
        if (txtOxygenLevel.getText().isBlank()) {
            isValid = false;
            hideShowValidation(lblOxygenLevelValidation, "Please enter Oxygen level");
            
        }
        
        if (txtRespiratoryRate.getText().isBlank()) {
            isValid = false;
            hideShowValidation(lblRespiratoryRateValidation, "Please enter Respiratory rate");
            
        } 
        
        if (txtBodyTemperature.getText().isBlank()) {
            isValid = false;
            hideShowValidation(lblBodyTemperatureValidation, "Please enter Body temperature");
            
        } 
        
        return isValid;
    }

    // Common function to hide show validation labels
    private void hideShowValidation(JLabel lbl, String errorMessage) {
        if (errorMessage.isBlank()) {
            lbl.setVisible(false);
        } else {
            lbl.setText(errorMessage);
            lbl.setVisible(true);
        }
        
    }
    
    private void clearData() {
        txtSYS.setText("");
        txtDIA.setText("");
        txtOxygenLevel.setText("");
        txtRespiratoryRate.setText("");
        txtBodyTemperature.setText("");
    }
    
    private void addVitalSigns() {
        VitalSigns vitalSign = new VitalSigns();
        
        vitalSign.setSys(Integer.parseInt(txtSYS.getText()));
        vitalSign.setDia(Integer.parseInt(txtDIA.getText()));
        vitalSign.setOxygenLevel(Integer.parseInt(txtOxygenLevel.getText()));
        vitalSign.setRespiratoryRate(txtRespiratoryRate.getText());
        vitalSign.setBodyTemperature(Double.valueOf(txtBodyTemperature.getText()));
        
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy - hh:mm:ss");
        Date date = new Date(); 
        
        vitalSign.setVisitTime(date);
        getAgeGroup(vitalSign);
        selectedPatient.encounterList.add(vitalSign);
        
        JOptionPane.showMessageDialog(this, "Vital signs added successfully");
        tblPatient.clearSelection();
        selectedPatient = new Patient();
        addVisitJPanel.setVisible(false);
    }
    
    public void getAgeGroup(VitalSigns vs){ //Checks the age value enterred by user and assigns the corresponding age group defined in the table
        if (selectedPatient.age < 1){
            vs.setAgeGroup("Infant");
        }
        else if (selectedPatient.age > 1 && selectedPatient.age <= 5){
            vs.setAgeGroup("Toddler");
        }
        else if (selectedPatient.age > 5 && selectedPatient.age <= 13){
            vs.setAgeGroup("Kid");
        }
        else if (selectedPatient.age > 13){
            vs.setAgeGroup("Adult");
        }
    }
    
}
